[package]
name = "embedded_surreal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.21"
proc-macro2 = "1.0.47"

[lib]
proc-macro = true
